pipeline {
    agent any
    stages {
        stage('nare') {
            steps {
                sh 'echo "Building..."'
            }
        }
        stage('new') {
            steps {
                sh 'echo "Testing..."'
            }
        }
        stage('job') {
            steps {
                sh 'echo "Deploying..."'
            }
        }
    }
}
